/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAdvanceFilter: typeof import('./src/components/BaseAdvanceFilter.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseDatable: typeof import('./src/components/BaseDatable.vue')['default']
    BaseDataTableButton: typeof import('./src/components/BaseDataTableButton.vue')['default']
    BaseDropdown: typeof import('./src/components/BaseDropdown.vue')['default']
    BaseFilter: typeof import('./src/components/BaseFilter.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BasePageHeader: typeof import('./src/components/BasePageHeader.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    ErrorCard: typeof import('./src/components/ErrorCard.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputLabelWithError: typeof import('./src/components/InputLabelWithError.vue')['default']
    ProgressModal: typeof import('./src/components/ProgressModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLabelWithError: typeof import('./src/components/SelectLabelWithError.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
